name: pytest

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-verison: [3.6, 3.7, 3.8, 3.9]
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Deps ${{ matrix.python-version }}
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint ${{ matrix.python-version }}
      run: |
        poetry run pylint *.py
    - name: Test
      run: |
        poetry run pytest
